mysite/musicband/urls.py
from django.urls import path
from . import views

app_name = "musicband"
urlpatterns = [
    path("", views.index, name="index"),
    path("records/", views.records, name="records"),
    path("about/", views.about, name="about"),
    path("<int:music_id>/", views.detail, name="detail"),
    path("<int:music_id>/vote/", views.vote, name="vote"),
    path('', views.musicband, name='musicband'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path("polls/", include("polls.urls", namespace="polls")),
    path('admin/', admin.site.urls),
    path('user_auth/', include("django.contrib.auth.urls")),
    path('user_auth/', include("user_auth.urls", namespace="user_auth")),
    path('', include("musicband.urls", namespace="musicband")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/polls/urls.py
from django.urls import path
from . import views

app_name = "polls"
urlpatterns = [
    # path("", views.index, name="home"),
    path("", views.index, name="index"),
    path("<int:question_id>/", views.detail, name="detail"),
    path("<int:question_id>/results/", views.results, name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
    path('', views.polls, name='polls'),
]

mysite/musicband/models.py
from django.db import models


# Create your models here.
class Music(models.Model):
    """Models are used to describe the data that must be stored for our app.
    Each attribute/variable of the model represents a database field.

    Music class variables : title, author, pub_date and image

    """
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    image = models.ImageField(upload_to='images')

    def __str__(self):
        """The __str__() method returns a string representation of an object.

           :return: title
        """
        return self.title


class Choice(models.Model):
    """Models are used to describe the data that must be stored for our app.
       Each attribute/variable of the model represents a database field.

       Choice class variables : music, choice_text and votes

    """
    music = models.ForeignKey(Music, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        """The __str__() method returns a string representation of an object.

            :return: choice_text
        """
        return self.choice_text

mysite/musicband/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from .models import Music, Choice
from django.template import loader


# Create your views here.
def index(request):
    """Function loads 'home' html page from template folder."""
    return render(request, "musicband/home.html")


def about(request):
    """Function loads 'about' html page from template folder."""
    return render(request, "musicband/about.html")


@login_required(login_url="/user_auth/login")
def records(request):
    """Function loads 'record' html page from template folder, the page is populated with records from the database.
    Records are presented by date. "@login_required" Decorator for views (login_required function from user_auth app)
    checks that the user is logged in, redirecting to the log-in page if necessary.

         :return: 'records' html page with dictionary of records

    """
    latest_record_list = Music.objects.order_by('-pub_date')[:5]
    context = {'latest_record_list': latest_record_list}
    return render(request, "musicband/records.html", context)


def musicband(request):
    """Function loads and return 'home' html page from template folder"""
    template = loader.get_template('musicband/home.html')
    return HttpResponse(template.render())


#
def detail(request, music_id):
    music = get_object_or_404(Music, pk=music_id)
    return render(request, 'musicband/detail.html', {'music': music})


# @login_required(login_url="/user_auth/login")
def vote(request, music_id):
    music = get_object_or_404(Music, pk=music_id)
    try:
        selected_choice = music.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the music voting form.
        return render(
            request,
            "musicband/detail.html",
            {
                "music": music,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("musicband:index", args=(music.id,)))

mysite/musicband/templates/musicband/about.html
{% extends "index.html" %}
{% block content %}
<div class="container" style="margin-top: 25px;">
 <div class="p-5 mb-4 bg-body-tertiary rounded-3">
      <div class="container-fluid py-5">
        <h2 class="display-5 fw-bold">Biography</h2>

          <div class="row">
    <div class="col-xl-6 col-lg-6 col-md-6" style="border:1px solid
#ddd">
      <img src="https://d10j3mvrs1suex.cloudfront.net/s:bzglfiles/u/404095/6a47d4522e480185530bdab1e65a0b8d64caeee6/original/2b4a2242-copy-2.jpg/!!/b%3AW1sicmVzaXplIiw2NjBdLFsibWF4Il0sWyJ3ZSJdXQ%3D%3D/meta%3AeyJzcmNCdWNrZXQiOiJiemdsZmlsZXMifQ%3D%3D.jpg" alt=".." class="img-fluid">
    </div>
    <div class="col-xl-6 col-lg-6 col-md-6" style="border:1px solid
#ddd">

      <p>After more than 25 years in music, building an unimpeachable reputation as a truly independent artist and entrepreneur, Julian Taylor now owns his legacy.
          From the formative rock of Staggered Crossing to the genre fusion of Julian Taylor Band, and now his revered work as a solo singer-songwriter, Julian owns the rights to it all, and it couldn’t have happened at a better time.</p>
      <p>It’s rare in this era to see an artist build slowly and reach a new level of widespread acclaim two decades into their career.
          But Julian’s ethos, work ethic, and artistry have always had a timeless quality to them.</p>
    </div>
  </div>


      </div>
    </div>

</div>

{% endblock %}

mysite/musicband/templates/musicband/detail.html
{% extends "index.html" %}
{% block content %}

<form class="row g-3" style="margin:20px;" action="{% url 'musicband:vote' music.id %}" method="post">
{% csrf_token %}
<fieldset class="col-md-6">

    <legend><h1>{{ music.title }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in music.choice_set.all %}

    <div class="col-12">
        <ul class="list-group">
            <li class="list-group-item">
            <span class="pull-right">
    <div class="form-check">
        <input class="form-check-input" type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label class="form-check-label" for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
           </div>
            </span>
            </li>
        </ul>

    </div>
    {% endfor %}
</fieldset>
<div class="col-12">
<button type="submit" class="btn btn-primary" value="Vote">Vote</button>
</div>

</form>
{% endblock %}

mysite/musicband/templates/musicband/home.html
{% extends "index.html" %}
{% block content %}

   <style>
     .carousel-inner img {
  width: 100%; /* Set width to 100% */
  margin: auto;
}

.carousel-caption h3 {
  color: #fff !important;
}

@media (max-width: 600px) {
  .carousel-caption {
    display: none; /* Hide the carousel text when the screen is less than 600 pixels wide */
  }
}
     </style>

<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="https://d10j3mvrs1suex.cloudfront.net/s:bzglfiles/u/404095/da57120e96f412f4f961628596bd6ed0c8d64d88/original/2b4a2210-copy-2.jpg/!!/b%3AW1sicmVzaXplIiwxODAwXSxbIm1heCJdLFsid2UiXV0%3D/meta%3AeyJzcmNCdWNrZXQiOiJiemdsZmlsZXMifQ%3D%3D.jpg" alt="http link">
      <div class="carousel-caption">
        <h1>Julian Taylor</h1>
        <h2>Welcome.....</h2>
      </div>
    </div>




  </div>


</div>
{% endblock %}

mysite/musicband/templates/musicband/records.html
{% extends "index.html" %} {% block content %}
<style>
  .test {
    margin: 0;
    margin-right: -50%;
    transform: translate(-50%, -50%)
    position: absolute;

  }
</style>
<div class="test">
<div class="container">
  <div class="row "  style="margin-top: 25px">
    <h1>The Best of Julian Taylor</h1>
    <ul class="list-group ">
      {% for music in latest_record_list %}

      <li class="list-group">
        <div class="card mb-3" style="max-width: 540px">
          <div class="row g-0">
            <div class="col-md-4">
              <img
                src="/media/{{music.image}}"
                class="img-fluid rounded-start"
                alt="..."
              />
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title">{{music.title}}</h5>
                <p class="card-text">{{music.author}}</p>
                <p class="card-text">{{music.pub_date}}</p>


                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                  <small class="text-body-secondary"
                    >HyperionDev Records
                  </small
                  >
                </div>
              </div>
            </div>
          </div>
        </div>
      </li>

      {% endfor %}
    </ul>
  </div>
</div>
  </div>
{% endblock %}