mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path("polls/", include("polls.urls", namespace="polls")),
    path('admin/', admin.site.urls),
    path('user_auth/', include("django.contrib.auth.urls")),
    path('user_auth/', include("user_auth.urls", namespace="user_auth")),
    path('', include("musicband.urls", namespace="musicband")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/polls/urls.py
from django.urls import path
from . import views

app_name = "polls"
urlpatterns = [
    # path("", views.index, name="home"),
    path("", views.index, name="index"),
    path("<int:question_id>/", views.detail, name="detail"),
    path("<int:question_id>/results/", views.results, name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
    path('', views.polls, name='polls'),
]

mysite/user_auth/urls.py
from django.shortcuts import render, redirect
from django.template.defaulttags import url
from django.urls import path, re_path, include
from . import views

app_name = "user_auth"

urlpatterns = [
    path("login", views.user_login, name='login'),
    path('authenticate_user/', views.authenticate_user, name='authenticate_user'),
    path('access/', views.show_user, name='show_user'),
    path('', views.create_user, name='register'),
    # path('', views.user_auth, name='sign'),
    # path('', views.user_auth, name='reg'),

    # re_path(r'^polls/', lambda request: redirect(request, 'polls/poll.html'), name="poll")
    # re_path(r"^$", include("polls.urls"), name="test"),
    # re_path(r"^polls", 'polls.views.index'),
    #url(r'^polls/', 'polls.views.index',  name="poll"),

]

mysite/user_auth/models.py
from django.db import models

# Create your models here.

mysite/user_auth/forms.py
from django import forms
from django.contrib.auth.models import User


class UserRegistrationForm(forms.Form):
    username = forms.CharField(label='Username', max_length=100, min_length=5,
                               widget=forms.TextInput(attrs={'class': 'form-control'}))
    firstname = forms.CharField(label='Firstname', max_length=100, min_length=5,
                                widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label='Password', max_length=50, min_length=5,
                                widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='Confirm Password',
                                max_length=50, min_length=8,
                                widget=forms.PasswordInput(attrs={'class': 'form-control'}))

mysite/user_auth/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.urls import reverse
from django.contrib.auth.models import User
from .forms import UserRegistrationForm
from django.contrib import messages
from django.template import loader


# Create your views here.
def user_login(request):
    # return HttpResponse("Hello world. You're at the auth index.")
    return render(request, 'authentication/login.html')


def sign(request):
    template = loader.get_template('authentication/login.html')
    return HttpResponse(template.render())


def reg(request):
    template = loader.get_template('authentication/register.html')
    return HttpResponse(template.render())


def authenticate_user(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    user = authenticate(username=username, password=password)
    if user is None:
        return HttpResponseRedirect(reverse('user_auth:login'))
    else:
        login(request, user)
        return HttpResponseRedirect(reverse('musicband:records'))


def show_user(request):
    print(request.user.username)
    return render(request, 'authentication/user.html', {
        "username": request.user.username,
        "password": request.user.password})
    # return render(request, "polls/poll.html")


def create_user(request):
    if request.method == 'POST':
        check1 = False
        check2 = False
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            firstname = form.cleaned_data['firstname']
            password1 = form.cleaned_data['password1']
            password2 = form.cleaned_data['password2']

            if password1 != password2:
                check1 = True
                messages.error(request, 'Password did not match!',
                               extra_tags='alert alert-warning alert-dismissible fade show')
            if User.objects.filter(username=username).exists():
                check2 = True
                messages.error(request, 'Username already exists!',
                               extra_tags='alert alert-warning alert-dismissible fade show')

            if check1 or check2:
                messages.error(
                    request, "Registration Failed!", extra_tags='alert alert-warning alert-dismissible fade show')
                return redirect('user_auth:register')
            else:
                user = User.objects.create_user(
                    username=username, password=password1, email=None, first_name=firstname)
                messages.success(
                    request, f'Thanks for registering {user.username}.',
                    extra_tags='alert alert-success alert-dismissible fade show')
                return redirect('user_auth:login')
    else:
        form = UserRegistrationForm()
    return render(request, 'authentication/register.html', {'form': form})


def test(request):
    # return HttpResponse("Hello world. You're at the auth index.")
    return redirect(request, 'polls/poll.html')

mysite/user_auth/templates/authentication/login.html
{% extends 'base.html' %}
{% block content %}
<style>
    .form-signin {
  max-width: 330px;
  padding: 1rem;
}

.form-signin .form-floating:focus-within {
  z-index: 2;
}

.form-signin input[type="text"] {
  margin-bottom: -1px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}

.form-signin input[type="password"] {
  margin-bottom: 10px;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}
</style>
<div class="container">
    <div class="row center">
        <div class="form-signin w-100 m-auto">
            <h1 class="h3 mb-3 fw-normal">Please sign in</h1>
            <form action="{% url 'user_auth:authenticate_user' %}" method="post">
                {% csrf_token %}
            <div class="form-floating">
          <input type="text" name="username"  class="form-control" id="floatingInput" placeholder="User name">
          <label for="floatingInput">Username</label>
        </div>
        <div class="form-floating">
          <input type="password" name="password" class="form-control" id="floatingPassword" placeholder="Password">
          <label for="floatingPassword">Password</label>
        </div>

        <button class="btn btn-primary w-100 py-2" type="submit">Sign in</button>
            </form>
            <p style="margin-top:20px;">Dont have an account? <a href="{% url 'user_auth:register' %}">Register Here</a></p>
        </div>
    </div>
</div>
<main class="form-signin w-100 m-auto">
  <form>


  </form>
</main>

{% endblock %}

mysite/user_auth/templates/authentication/register.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row center">
        <div class="col-md-6 offset-md-3">
            <p style="margin-top:20px;">Already have an account? <a href="{% url 'user_auth:login' %}">Login Here</a></p>
            {% if messages %}
            <div class="messages">
                {% for message in messages %}
                <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endfor %}
            </div>
            {% endif %}
            <form action="" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Sign Up</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

mysite/user_auth/templates/authentication/user.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row center">
        <div class="col-md-6 offset-md-3">
            <h1 style="margin-top:20px;"> Welcome, {{username}} </h1>

 <p style="font-size: 20px;margin-top:10px;">See available polls <a class="btn btn-primary"  role="button" href="{% url 'polls:polls' %}">Click Here</a></p>
        </div>
    </div>
</div>

{% endblock %}