mysite/musicband/urls.py
from django.urls import path
from . import views

app_name = "musicband"
urlpatterns = [
    path("", views.index, name="index"),
    path("records/", views.records, name="records"),
    path("about/", views.about, name="about"),
    path("<int:music_id>/", views.detail, name="detail"),
    path("<int:music_id>/vote/", views.vote, name="vote"),
    path('', views.musicband, name='musicband'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path("polls/", include("polls.urls", namespace="polls")),
    path('admin/', admin.site.urls),
    path('user_auth/', include("django.contrib.auth.urls")),
    path('user_auth/', include("user_auth.urls", namespace="user_auth")),
    path('', include("musicband.urls", namespace="musicband")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/polls/urls.py
from django.urls import path
from . import views

app_name = "polls"
urlpatterns = [
    # path("", views.index, name="home"),
    path("", views.index, name="index"),
    path("<int:question_id>/", views.detail, name="detail"),
    path("<int:question_id>/results/", views.results, name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
    path('', views.polls, name='polls'),
]

mysite/user_auth/urls.py
from django.shortcuts import render, redirect
from django.template.defaulttags import url
from django.urls import path, re_path, include
from . import views

app_name = "user_auth"

urlpatterns = [
    path("login", views.user_login, name='login'),
    path('authenticate_user/', views.authenticate_user, name='authenticate_user'),
    path('access/', views.show_user, name='show_user'),
    path('', views.create_user, name='register'),
    # path('', views.user_auth, name='sign'),
    # path('', views.user_auth, name='reg'),

    # re_path(r'^polls/', lambda request: redirect(request, 'polls/poll.html'), name="poll")
    # re_path(r"^$", include("polls.urls"), name="test"),
    # re_path(r"^polls", 'polls.views.index'),
    #url(r'^polls/', 'polls.views.index',  name="poll"),

]

mysite/musicband/models.py
from django.db import models


# Create your models here.
class Music(models.Model):
    """Models are used to describe the data that must be stored for our app.
    Each attribute/variable of the model represents a database field.

    Music class variables : title, author, pub_date and image

    """
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    image = models.ImageField(upload_to='images')

    def __str__(self):
        """The __str__() method returns a string representation of an object.

           :return: title
        """
        return self.title


class Choice(models.Model):
    """Models are used to describe the data that must be stored for our app.
       Each attribute/variable of the model represents a database field.

       Choice class variables : music, choice_text and votes

    """
    music = models.ForeignKey(Music, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        """The __str__() method returns a string representation of an object.

            :return: choice_text
        """
        return self.choice_text

mysite/musicband/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from .models import Music, Choice
from django.template import loader


# Create your views here.
def index(request):
    """Function loads 'home' html page from template folder."""
    return render(request, "musicband/home.html")


def about(request):
    """Function loads 'about' html page from template folder."""
    return render(request, "musicband/about.html")


@login_required(login_url="/user_auth/login")
def records(request):
    """Function loads 'record' html page from template folder, the page is populated with records from the database.
    Records are presented by date. "@login_required" Decorator for views (login_required function from user_auth app)
    checks that the user is logged in, redirecting to the log-in page if necessary.

         :return: 'records' html page with dictionary of records

    """
    latest_record_list = Music.objects.order_by('-pub_date')[:5]
    context = {'latest_record_list': latest_record_list}
    return render(request, "musicband/records.html", context)


def musicband(request):
    """Function loads and return 'home' html page from template folder"""
    template = loader.get_template('musicband/home.html')
    return HttpResponse(template.render())


#
def detail(request, music_id):
    music = get_object_or_404(Music, pk=music_id)
    return render(request, 'musicband/detail.html', {'music': music})


# @login_required(login_url="/user_auth/login")
def vote(request, music_id):
    music = get_object_or_404(Music, pk=music_id)
    try:
        selected_choice = music.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the music voting form.
        return render(
            request,
            "musicband/detail.html",
            {
                "music": music,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("musicband:index", args=(music.id,)))

mysite/musicband/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">

    <title>Music</title>
</head>

<body style="background-color: lightblue;">
    <header>
 <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <!-- Container wrapper -->
  <div class="container-fluid">
    <!-- Toggle button -->
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarCenteredExample"
      aria-controls="navbarCenteredExample"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div
      class="collapse navbar-collapse justify-content-center"
      id="navbarCenteredExample"
    >
      <!-- Left links -->
      <ul class="navbar-nav mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'musicband:musicband' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'musicband:about' %}">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'musicband:records' %}">Records</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'user_auth:login' %}">Sign in</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'user_auth:register' %}">Register</a>
        </li>


      </ul>
      <!-- Left links -->
    </div>
    <!-- Collapsible wrapper -->
  </div>
  <!-- Container wrapper -->
</nav>
    </header>

    <main role="main">

<div id="content">
        {% block content %}{% endblock %}
    </div>
    </main>
<script src="/docs/5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>